# Generated by Django 5.0.3 on 2024-03-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedtests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speedtest',
            name='user',
        ),
    ]
